#
# continuous integration workflow
#
name: build repo

on:
 push:
    branches: [ master]
 pull_request:
    branches: [ master]
 workflow_dispatch:
    branches: [ master]

jobs:
  build_focal_noetic:
    runs-on: ubuntu-20.04
    name: build under ROS1 noetic on Focal (x86_64)
    container:
      image: berndpfrommer/focal_noetic
    steps:
      - name: check out github repo
        uses: actions/checkout@v3
        with:
          path: src/event_array_py
          fetch-depth: 0
      - name: compile from source
        run: ./src/event_array_py/.github/scripts/build_ros1.bash

  build_focal_galactic:
    runs-on: ubuntu-20.04
    container:
      image: berndpfrommer/focal_galactic
    name: build under ROS2 on Focal (x86_64)
    steps:
      - name: check out github repo
        uses: actions/checkout@v3
        with:
          path: src/event_array_py
          fetch-depth: 0
      - name: compile from source
        run: ./src/event_array_py/.github/scripts/build_ros2.bash
  build_jammy_humble:
    runs-on: ubuntu-22.04
    container:
      image: berndpfrommer/jammy_humble
    name: build under ROS2 humble on Jammy (x86_64)
    steps:
      - name: check out github repo
        uses: actions/checkout@v3
        with:
          path: src/event_array_py
          fetch-depth: 0
      - name: compile from source
        run: ./src/event_array_py/.github/scripts/build_ros2.bash
